---
- name: Check Ansible connectivity to localhost
  hosts: localhost
  connection: local # Important: Tells Ansible to run locally inside the container
  gather_facts: false
  tasks:
    - name: Ping localhost
      ansible.builtin.ping:
